### ISSUE TITLE
Some custom blurbs, taglines, and colors are missing

### ISSUE THREAD

**Issue by exaskye** [elytra/Site#1]
Paging @BBoldt @alexbobp @jamierocks 

Please give me a one-sentence tagline and a short paragraph for a blurb, as well as your favorite color from [this list](https://material.io/guidelines/style/color.html).

**Comment by exaskye** [comment]
Also paging @darkevilmac @DeGariless who are both still using my placeholder blurb. If they want to keep it that's fine, but I'd prefer custom blurbs.

**Comment by darkevilmac** [comment]
@unascribed I like the placeholder blurb as is.

**Comment by darkevilmac** [comment]
@BBoldt @alexbobp @jamierocks @DeGariless plz

**Comment by BBoldt** [comment]
#D500F9

"Stranded in the future."

"Makes experimental music. Used to make modpacks until they tried to eat his soul. Still comments on issues sometimes!"

**Comment by alexbobp** [comment]
keep the colors

"Language Connoisseur"

"Tries to make modpacks, then grumpily writes code to fill in the gaps.  Tries in vain to convince people that the best jvm programming language wasn't created in 1995."

**Comment by exaskye** [comment]
I think DeGariless is fine with the placeholder.
